Repository JOBIS-DEMU/DEMU_iOS, pull requests merged in 2024-10, with the labels that each got.

#2 merge :: 프로젝트 세팅
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Core/Sources/empty.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_HomeFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_HomeFalse.imageset/DEMU_HomeFalse.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_HomeTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_HomeTrue.imageset/DEMU_HomeTrue.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Logo.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Logo.imageset/DEMU_Logo.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_MyFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_MyFalse.imageset/DEMU_MyFalse.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_MyTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_MyTrue.imageset/DEMU_MyTrue.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Search.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Search.imageset/DEMU_SearchFalse.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Send.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_Send.imageset/send.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_VlogFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_VlogFalse.imageset/DEMU_VlogFalse.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_VlogTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_VlogTrue.imageset/DEMU_VlogTrue.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_checkBoxFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_checkBoxFalse.imageset/DEMU_checkBoxFalse.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_checkBoxTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_checkBoxTrue.imageset/DEMU_checkBoxTrue.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_eyeOff.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_eyeOff.imageset/eyeOff.svg
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_eyeOpen.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Images.xcassets/DEMU_eyeOpen.imageset/eyeOpen.svg
  Projects/Modules/DesignSystem/Sources/Extension/Color/UIColor+.swift
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
  Projects/Modules/DesignSystem/Sources/empty.swift
Labels: SETTING

#4 Feature/#3 onboarding
  .tuist-version
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Project.swift
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Feature/Sources/empty.swift
  Projects/Modules/DesignSystem/Derived/Sources/Button/DMButton.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/error.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/main1.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/text.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/textField.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_HomeFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_HomeFalse.imageset/DEMU_HomeFalse.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_HomeTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_HomeTrue.imageset/DEMU_HomeTrue.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Logo.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Logo.imageset/DEMU_Logo.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_MyFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_MyFalse.imageset/DEMU_MyFalse.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_MyTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_MyTrue.imageset/DEMU_MyTrue.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Search.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Search.imageset/DEMU_SearchFalse.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Send.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Send.imageset/send.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_VlogFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_VlogFalse.imageset/DEMU_VlogFalse.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_VlogTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_VlogTrue.imageset/DEMU_VlogTrue.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_checkBoxFalse.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_checkBoxFalse.imageset/DEMU_checkBoxFalse.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_checkBoxTrue.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_checkBoxTrue.imageset/DEMU_checkBoxTrue.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_eyeOff.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_eyeOff.imageset/eyeOff.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_eyeOpen.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_eyeOpen.imageset/eyeOpen.svg
  Projects/Modules/DesignSystem/Sources/Extension/Color/UIColor+.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
  Tuist/Dependencies/graph.json
Labels: FEAT

#7 fix :: 버튼 수정
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Tuist/Dependencies/graph.json
Labels: FIX

#8 feat :: 온보딩 그라데이션, textfield 컴포넌트 생성
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/background.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/gradient.colorset/Contents.json
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/DMTextFieldView.swift
  Projects/Modules/DesignSystem/Sources/Extension/Color/UIColor+.swift
  Tuist/Dependencies/graph.json
Labels: FEAT

#10 feat :: login VC
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/DMTextFieldView.swift
  Tuist/Dependencies/graph.json
Labels: FEAT

#13 feat :: loginVC publishing
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/back.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/back.imageset/back.svg
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/DMTextButtonView.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/DMTextFieldView.swift
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
  Tuist/Dependencies/graph.json
Labels: FEAT

#15 feat :: error label 추가
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
  Projects/Modules/DesignSystem/Sources/Component/TextField/DMTextFieldView.swift
Labels: FEAT

#17 feat :: 버튼 활성화 비활성화 추가
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Tuist/Dependencies/graph.json
Labels: FEAT

#26 Feature/#25 home vc
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Main/Home/ community/CommunityCell.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
Labels: FEAT

#27 Feature/#24 my page
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Main/MyPage/Introduce/DMTextView.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/NickNameChangeViewController/NickNameChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/PwdChangeViewController/PwdViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/SettingViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Colors/text2.colorset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Plus.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Plus.imageset/DEMU_Plus.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Profile.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Profile.imageset/DEMU_Profile.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_X.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_X.imageset/DEMU_X.svg
  Projects/Modules/DesignSystem/Sources/Component/Button/DMButtonView.swift
  Projects/Modules/DesignSystem/Sources/Component/Label/DMMyLabelView.swift
  Projects/Modules/DesignSystem/Sources/Component/View/DMBackView.swift
  Projects/Modules/DesignSystem/Sources/Extension/Color/UIColor+.swift
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
Labels: FEAT

#29 chore :: homeVC 수정
  Projects/Feature/Sources/Main/Home/HomeViewController.swift
Labels: CHORE

#32 Feature/#30 home vc tablecell
  Projects/Feature/Sources/Main/Home/ community/CommunityCell.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Bronze.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Bronze.imageset/DEMU_Bronze.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Diamond.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Diamond.imageset/DEMU_Diamond.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Gold.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Gold.imageset/DEMU_Gold.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Master.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Master.imageset/DEMU_Master.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Silver.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Silver.imageset/DEMU_Silver.svg
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
Labels: FEAT

#33 Feature/# search vc
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogCharViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatCell.swift
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogViewController.swift
  Projects/Feature/Sources/Main/Search/SearchViewController.swift
Labels: FEAT

#36 chore :: 수정
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
Labels: FEAT

#41 Feature/#40 write vc
  Projects/App/Project.swift
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
  Projects/Feature/Sources/Main/Search/SearchViewController.swift
  Projects/Feature/Sources/Main/TabBar/TabBarController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Down.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Down.imageset/DEMU_Down.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Image.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Image.imageset/DEMU_Image.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_ImageX.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_ImageX.imageset/DEMU_ImageX.svg
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Up.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Up.imageset/DEMU_Up.svg
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
Labels: FEAT

#42 Feature/#39 blogchat vc chore
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatCell.swift
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatViewController.swift
Labels: CHORE, FIX

#45 setting :: more_image 추가
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_More.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_More.imageset/DEMU_More.svg
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
Labels: SETTING

#47 Feature/#44 blog
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogModal/BlogModalCell.swift
  Projects/Feature/Sources/Main/Blog/BlogModal/BlogModalViewController.swift
Labels: CHORE, FEAT

#49 Feature/#46 post vc publishing
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
Labels: FEAT

#50 chore :: tabBar 수정
  Projects/Feature/Sources/Main/TabBar/TabBarController.swift
Labels: CHORE

#53 chore :: searchVC layout 수정
  Projects/Feature/Sources/Main/Search/SearchViewController.swift
Labels: CHORE

#55 Feature/#54 blog vc feature
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
Labels: FEAT

#58 Feature/#57 more
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Before.imageset/Contents.json
  Projects/Modules/DesignSystem/Resources/Assets.xcassets/Images/DEMU_Before.imageset/before.svg
  Projects/Modules/DesignSystem/Sources/Extension/Image/UIImage+.swift
Labels: CHORE, FEAT

#61 chore :: tabbar layout 수정
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
Labels: CHORE

#63 chore :: mypageC, homC layout 변경, mypageVC 뷰 이동
  Projects/Feature/Sources/Main/Home/ community/CommunityCell.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
Labels: CHORE

#64 Feature/#59 onboarding rx
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
Labels: SETTING

#66 chore :: rx로 변환, baseVC에 bindAction() 추가
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
Labels: CHORE

#70 home vc post vc mypage vc rx
  Projects/Feature/Sources/Main/Home/ community/CommunityCell.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
Labels: CHORE

#72 Feature/#71 blogchat vc blog vc rx
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
Labels: CHORE

#74 Feature/#73 setting vc rx
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/NickNameChangeViewController/NickNameChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/PwdChangeViewController/PwdViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/SettingViewController.swift
Labels: CHORE

#76 chore :: passwordchageVC 수정
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
Labels: CHORE

#78 Feature/#77 allfile rx
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Sources/Login/LoginViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/NickNameChangeViewController/NickNameChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/PwdChangeViewController/PwdViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/SettingViewController.swift
  Projects/Feature/Sources/Main/Search/SearchViewController.swift
  Projects/Feature/Sources/Main/TabBar/TabBarController.swift
  Projects/Feature/Sources/Onboarding/OnboardingViewController.swift
  Projects/Feature/Sources/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/PassWordChange/PassWordChangeViewController.swift
  Projects/Feature/Sources/SignUp/SignUpViewController.swift
Labels: CHORE

#81 Feature/#80 navigation identifier
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatCell.swift
  Projects/Feature/Sources/Main/Blog/BlogChat/BlogChatViewController.swift
  Projects/Feature/Sources/Main/Blog/BlogMain/BlogViewController.swift
  Projects/Feature/Sources/Main/Home/ community/CommunityCell.swift
  Projects/Feature/Sources/Main/Home/HomeMain/HomeViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/MyPageViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeCell.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/MajorChangeViewController/MajorChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/NickNameChangeViewController/NickNameChangeViewController.swift
  Projects/Feature/Sources/Main/MyPage/MyPageMain/Setting/PwdChangeViewController/PwdViewController.swift
  Projects/Feature/Sources/Main/TabBar/TabBarController.swift
Labels: REFACT

#82 Feature/#79 login api
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Feature/Sources/Auth/Api/AuthAPI.swift
  Projects/Feature/Sources/Auth/Login/LoginViewController.swift
  Projects/Feature/Sources/Auth/Login/LoginViewModel.swift
  Projects/Feature/Sources/Auth/Onboarding/OnboardingViewController.swift
  Projects/Feature/Sources/Auth/PassWordChange/EmailSendViewController.swift
  Projects/Feature/Sources/Auth/PassWordChange/PassWordChangeViewController.swift
  Projects/Feature/Sources/Auth/SignUp/SignUpViewController.swift
  Projects/Feature/Sources/Main/Home/Post/MoreViewController.swift
  Projects/Feature/Sources/Main/Home/Post/PostViewController.swift
  Projects/Feature/Sources/Networking/Data/SignupInfo.swift
  Projects/Feature/Sources/Networking/Header/Header.swift
  Projects/Feature/Sources/Networking/Model/AuthModel.swift
  Projects/Feature/Sources/Networking/Plugin/MoyaPlugin.swift
  Projects/Feature/Sources/Networking/Plugin/ServiceType.swift
  Projects/Feature/Sources/Networking/Protocol/ViewModelType.swift
  Projects/Feature/Sources/Networking/Service/AuthService.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
Labels: CHORE, FEAT

#88 Feature/#87 auth
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Feature/Sources/Auth/Api/AuthAPI.swift
  Projects/Feature/Sources/Auth/Login/LoginViewModel.swift
  Projects/Feature/Sources/Networking/Data/Storage.swift
  Projects/Feature/Sources/Networking/Header/Header.swift
  Projects/Feature/Sources/Networking/Model/TokenModel.swift
Labels: CHORE

#92 Feature/#90 login api
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Feature/Sources/Auth/Api/AuthAPI.swift
  Projects/Feature/Sources/Auth/Login/LoginViewController.swift
  Projects/Feature/Sources/Auth/Login/LoginViewModel.swift
  Projects/Feature/Sources/Networking/Header/Header.swift
  Projects/Feature/Sources/Networking/Service/AuthService.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
Labels: FEAT

#98 setting :: Kingfisher 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
Labels: SETTING
